name: Deploy

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: '14.9.0'
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn build
    - name: Rename cv.md to index.md
      run: mv cv.md index.md
    - name: Move files from dist directory into root
      run: mv dist/* .
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./
        allow_empty_commit: true
        force_orphan: true
        enable_jekyll: true
